version: "3"

services:
  api:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - 8000:8000
    volumes:
      - ./app:/src
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
      TZ: Asia/Tokyo
